name: PeTTa CI

on:
  push:
    branches:
      - main
      - feat/workflow-Integration
  pull_request:
    branches:
      - main
      - feat/workflow-Integration

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install SWI-Prolog
        run: |
            sudo apt update
            sudo apt install -y swi-prolog

      - name: Clone PeTTa
        run: |
          git clone https://github.com/patham9/PeTTa.git
          cd PeTTa
          chmod +x run.sh
          echo "$PWD" >> $GITHUB_PATH

      - name: Verify run.sh
        run: |
          which run.sh
          swipl --version

      - name: Run Test Suite
        run: |
          python3 scripts/run-tests.py